# Generated by Django 2.2.6 on 2021-12-23 15:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('Euro', 'Euro'), ('zl', 'PLN')], max_length=25)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=19)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='BudgetsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List of budgets',
                'verbose_name_plural': 'Lists of budgets',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgets_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_permissions', to='budget.BudgetsList')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits_obtained', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared permission',
                'verbose_name_plural': 'Shared permissions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BudgetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Minimum amount - 0.01')])),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_operations', to='budget.Budget')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_operations', to='budget.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget operation',
                'verbose_name_plural': 'Budget operations',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget.BudgetsList'),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
    ]
