# Generated by Django 2.2.6 on 2021-12-21 20:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('Euro', 'Euro'), ('zl', 'PLN')], max_length=25)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BudgetsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List of budgets',
                'verbose_name_plural': 'Lists of budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_operations', to='budget.Budget')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Category')),
            ],
            options={
                'verbose_name': 'Budget operation',
                'verbose_name_plural': 'Budget operations',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget.BudgetsList'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
    ]
